// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB_fxlhGwS9KxzH5bcIb6YypwXcEONTj4',
    appId: '1:1072016233070:web:9cbe3fd219c5ea67a78c7f',
    messagingSenderId: '1072016233070',
    projectId: 'marte-training',
    authDomain: 'marte-training.firebaseapp.com',
    storageBucket: 'marte-training.firebasestorage.app',
    measurementId: 'G-2TFZ46QWS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkdrVAkRF7t-xKIsyQMICUpr1jHTY9gtY',
    appId: '1:1072016233070:android:7aa3db01e94a580da78c7f',
    messagingSenderId: '1072016233070',
    projectId: 'marte-training',
    storageBucket: 'marte-training.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFgpC9nXSyRibfK_WXyuU71830keE_LGU',
    appId: '1:1072016233070:ios:9cac4cffb2b94947a78c7f',
    messagingSenderId: '1072016233070',
    projectId: 'marte-training',
    storageBucket: 'marte-training.firebasestorage.app',
    iosBundleId: 'com.example.marteTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFgpC9nXSyRibfK_WXyuU71830keE_LGU',
    appId: '1:1072016233070:ios:9cac4cffb2b94947a78c7f',
    messagingSenderId: '1072016233070',
    projectId: 'marte-training',
    storageBucket: 'marte-training.firebasestorage.app',
    iosBundleId: 'com.example.marteTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB_fxlhGwS9KxzH5bcIb6YypwXcEONTj4',
    appId: '1:1072016233070:web:95b5d519fd53a7f3a78c7f',
    messagingSenderId: '1072016233070',
    projectId: 'marte-training',
    authDomain: 'marte-training.firebaseapp.com',
    storageBucket: 'marte-training.firebasestorage.app',
    measurementId: 'G-26Y6L5T9Y5',
  );
}
